openapi: '3.0.1'
info:
  version: '1.0.0'
  title: Checkout.com API Reference
  x-logo:
    url: "https://assets.checkout.com/docs/logos/checkout-api-reference-logo.svg"
    backgroundColor: "#F0F3F7"
    altText: "Checkout.com API logo"
  contact:
    name: Checkout.com Support
    url: 'https://checkout.com'
    email: support@checkout.com
  license:
    name: Checkout.com
    url: 'https://checkout.com/api/license/'
  termsOfService: 'https://checkout.com/terms/'
  description: >
    # Introduction
    
    Checkout.com provides a collection of APIs that enable you to process and manage payments.  
    
    Our APIs accept and return JSON in the HTTP body and return HTTP response codes to indicate errors. You can consume the APIs directly using your favorite HTTP/REST library or make use of one of our <a href="https://docs.checkout.com/docs/sdks" target="_blank">SDKs</a>.  
    

    Our unified payments API allows you to accept payments from cards, digital wallets and the most popular alternative payment methods, as well as pay out to a variety of destinations, all using the same integration. 
    
    
    And with our webhook management, events and disputes APIs, you can keep on top of your transactions and react to any chargebacks, keeping your business running smoothly. 
    
    # Authentication
    
    When you sign up for an account, you are given an OAuth 2.0 access key ID and secret that can be used to generate access tokens to authenticate with our API.  


    Never share your access key credentials. Keep them guarded and secure.
servers:
  - url: https://api.checkout.com
    description: Live API
  - url: https://api.sandbox.checkout.com
    description: Sandbox API
tags:
  - name: Access
  - name: Payments
    description: Process and manage payments from a variety of sources and to various destinations all within one integration.
  # - name: Sources
  #   description: Create a payment source for a customer that you can use for one or more payments.
  - name: Tokens
    description: Create a token that represents a card's details (or their tokenized form in a digital wallet) that you can later use to request a payment, without you having to process or store any sensitive information.
  - name: Instruments
    description: Create a payment instrument that you can later use as the source or destination for one or more payments.
  - name: Forex
    description: Checkout.com Foreign Exchange services
  - name: Disputes
    description: Keep track of and act on your open disputes (also known as chargebacks) to submit the best possible response.
  - name: Marketplace
    description: Manage all your sub-entities (also known as sub-merchants) through one integration, globally.
  - name: Sessions
    description: Sessions are Checkout.com's interpretation of the EMV 3DS protocol which enables support for SCA payments.
  - name: Workflows
  # - name: Files
  #   description: |
  #     Upload files to be used as input to other APIs

# x-tagGroups:
# - name: Flow
#   tags:
#     - Events
#     - Workflows